      - name: Check project files
        shell: pwsh
        run: |
          Write-Host "Current folder:"
          Get-Location
          Write-Host "Python files found:"
          Get-ChildItem -Path . -Recurse -File -Filter "*.py" | ForEach-Object {
            Write-Host $_.FullName
          }

      - name: Build EXE
        shell: pwsh
        run: |
          pyinstaller --onefile --windowed --name "Galaxy Defender" "galaxy_defender.py"
